/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.illinois.nondex.gradle.plugin;

import edu.illinois.nondex.gradle.plugin.tasks.NonDexHelp;
import edu.illinois.nondex.gradle.plugin.tasks.NonDexTest;
import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class NondexGradlePlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.getTasks().register("greeting", task -> {
            task.doLast(s -> System.out.println("Hello from plugin 'edu.illinois.NondexGradlePlugin'"));
        });
        project.getTasks().create(NonDexHelp.TASK_NAME, NonDexHelp.class).init();
        project.getTasks().create(NonDexTest.TASK_NAME, NonDexHelp.class).init();
    }
}
